name: Release

on:
  release:
    types: [created]

jobs:
  build-and-publish-image:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Buildx setup
        uses: docker/setup-buildx-action@v3
      - name: Run Buildx build and push
        uses: docker/build-push-action@v6
        with:
          tags: c-w-o/arma3server:${{ github.event.release.tag_name }}
          push: false
          load: false
          outputs: type=docker,dest=/tmp/arma3server-${{ github.event.release.tag_name }}.tar
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            /tmp/arma3server-${{ github.event.release.tag_name }}.tar